// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pFile/QuotationMessage.proto

package org.sky.framework.test.protobuf;

public final class QuotationMessage {
  private QuotationMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QuotationPackOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string tradingDate = 1;
    /**
     * <code>required string tradingDate = 1;</code>
     */
    boolean hasTradingDate();
    /**
     * <code>required string tradingDate = 1;</code>
     */
    String getTradingDate();
    /**
     * <code>required string tradingDate = 1;</code>
     */
    com.google.protobuf.ByteString
        getTradingDateBytes();

    // required .QuotationPack.SecuType secuType = 2 [default = Other];
    /**
     * <code>required .QuotationPack.SecuType secuType = 2 [default = Other];</code>
     */
    boolean hasSecuType();
    /**
     * <code>required .QuotationPack.SecuType secuType = 2 [default = Other];</code>
     */
    org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType getSecuType();

    // repeated .QuotationPack.Quotation quotes = 3;
    /**
     * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
     */
    java.util.List<org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation>
        getQuotesList();
    /**
     * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
     */
    org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation getQuotes(int index);
    /**
     * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
     */
    int getQuotesCount();
    /**
     * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
     */
    java.util.List<? extends org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.QuotationOrBuilder>
        getQuotesOrBuilderList();
    /**
     * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
     */
    org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.QuotationOrBuilder getQuotesOrBuilder(
		    int index);
  }
  /**
   * Protobuf type {@code QuotationPack}
   */
  public static final class QuotationPack extends
      com.google.protobuf.GeneratedMessage
      implements QuotationPackOrBuilder {
    // Use QuotationPack.newBuilder() to construct.
    private QuotationPack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QuotationPack(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QuotationPack defaultInstance;
    public static QuotationPack getDefaultInstance() {
      return defaultInstance;
    }

    public QuotationPack getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QuotationPack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              tradingDate_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType value = org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                secuType_ = value;
              }
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                quotes_ = new java.util.ArrayList<org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation>();
                mutable_bitField0_ |= 0x00000004;
              }
              quotes_.add(input.readMessage(org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          quotes_ = java.util.Collections.unmodifiableList(quotes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sky.framework.test.protobuf.QuotationMessage.internal_static_QuotationPack_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sky.framework.test.protobuf.QuotationMessage.internal_static_QuotationPack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.class, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Builder.class);
    }

    public static com.google.protobuf.Parser<QuotationPack> PARSER =
        new com.google.protobuf.AbstractParser<QuotationPack>() {
      public QuotationPack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuotationPack(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<QuotationPack> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code QuotationPack.SecuType}
     */
    public enum SecuType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SZ_Index = 1;</code>
       */
      SZ_Index(0, 1),
      /**
       * <code>SZ_Stock = 2;</code>
       */
      SZ_Stock(1, 2),
      /**
       * <code>SZ_Bond = 3;</code>
       */
      SZ_Bond(2, 3),
      /**
       * <code>SZ_Fund = 4;</code>
       */
      SZ_Fund(3, 4),
      /**
       * <code>Other = 5;</code>
       */
      Other(4, 5),
      /**
       * <code>CSIndex = 6;</code>
       */
      CSIndex(5, 6),
      /**
       * <code>CSIopv = 7;</code>
       */
      CSIopv(6, 7),
      /**
       * <code>SH_Index = 8;</code>
       */
      SH_Index(7, 8),
      /**
       * <code>SH_Stock = 9;</code>
       */
      SH_Stock(8, 9),
      /**
       * <code>SH_Bond = 10;</code>
       */
      SH_Bond(9, 10),
      /**
       * <code>SH_Fund = 11;</code>
       */
      SH_Fund(10, 11),
      ;

      /**
       * <code>SZ_Index = 1;</code>
       */
      public static final int SZ_Index_VALUE = 1;
      /**
       * <code>SZ_Stock = 2;</code>
       */
      public static final int SZ_Stock_VALUE = 2;
      /**
       * <code>SZ_Bond = 3;</code>
       */
      public static final int SZ_Bond_VALUE = 3;
      /**
       * <code>SZ_Fund = 4;</code>
       */
      public static final int SZ_Fund_VALUE = 4;
      /**
       * <code>Other = 5;</code>
       */
      public static final int Other_VALUE = 5;
      /**
       * <code>CSIndex = 6;</code>
       */
      public static final int CSIndex_VALUE = 6;
      /**
       * <code>CSIopv = 7;</code>
       */
      public static final int CSIopv_VALUE = 7;
      /**
       * <code>SH_Index = 8;</code>
       */
      public static final int SH_Index_VALUE = 8;
      /**
       * <code>SH_Stock = 9;</code>
       */
      public static final int SH_Stock_VALUE = 9;
      /**
       * <code>SH_Bond = 10;</code>
       */
      public static final int SH_Bond_VALUE = 10;
      /**
       * <code>SH_Fund = 11;</code>
       */
      public static final int SH_Fund_VALUE = 11;


      public final int getNumber() { return value; }

      public static SecuType valueOf(int value) {
        switch (value) {
          case 1: return SZ_Index;
          case 2: return SZ_Stock;
          case 3: return SZ_Bond;
          case 4: return SZ_Fund;
          case 5: return Other;
          case 6: return CSIndex;
          case 7: return CSIopv;
          case 8: return SH_Index;
          case 9: return SH_Stock;
          case 10: return SH_Bond;
          case 11: return SH_Fund;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SecuType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<SecuType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SecuType>() {
              public SecuType findValueByNumber(int number) {
                return SecuType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.getDescriptor().getEnumTypes().get(0);
      }

      private static final SecuType[] VALUES = values();

      public static SecuType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private SecuType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:QuotationPack.SecuType)
    }

    public interface QuotationOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // repeated string value = 1;
      /**
       * <code>repeated string value = 1;</code>
       */
      java.util.List<String>
      getValueList();
      /**
       * <code>repeated string value = 1;</code>
       */
      int getValueCount();
      /**
       * <code>repeated string value = 1;</code>
       */
      String getValue(int index);
      /**
       * <code>repeated string value = 1;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes(int index);
    }
    /**
     * Protobuf type {@code QuotationPack.Quotation}
     */
    public static final class Quotation extends
        com.google.protobuf.GeneratedMessage
        implements QuotationOrBuilder {
      // Use Quotation.newBuilder() to construct.
      private Quotation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Quotation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Quotation defaultInstance;
      public static Quotation getDefaultInstance() {
        return defaultInstance;
      }

      public Quotation getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Quotation(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  value_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000001;
                }
                value_.add(input.readBytes());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = new com.google.protobuf.UnmodifiableLazyStringList(value_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sky.framework.test.protobuf.QuotationMessage.internal_static_QuotationPack_Quotation_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sky.framework.test.protobuf.QuotationMessage.internal_static_QuotationPack_Quotation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.class, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder.class);
      }

      public static com.google.protobuf.Parser<Quotation> PARSER =
          new com.google.protobuf.AbstractParser<Quotation>() {
        public Quotation parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Quotation(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Quotation> getParserForType() {
        return PARSER;
      }

      // repeated string value = 1;
      public static final int VALUE_FIELD_NUMBER = 1;
      private com.google.protobuf.LazyStringList value_;
      /**
       * <code>repeated string value = 1;</code>
       */
      public java.util.List<String>
          getValueList() {
        return value_;
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public String getValue(int index) {
        return value_.get(index);
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes(int index) {
        return value_.getByteString(index);
      }

      private void initFields() {
        value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < value_.size(); i++) {
          output.writeBytes(1, value_.getByteString(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < value_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(value_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getValueList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code QuotationPack.Quotation}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.QuotationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.sky.framework.test.protobuf.QuotationMessage.internal_static_QuotationPack_Quotation_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.sky.framework.test.protobuf.QuotationMessage.internal_static_QuotationPack_Quotation_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.class, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder.class);
        }

        // Construct using hbec.app.quotation.stream.message.QuotationMessage.QuotationPack.Quotation.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.sky.framework.test.protobuf.QuotationMessage.internal_static_QuotationPack_Quotation_descriptor;
        }

        public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation getDefaultInstanceForType() {
          return org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.getDefaultInstance();
        }

        public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation build() {
          org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation buildPartial() {
          org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation result = new org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = new com.google.protobuf.UnmodifiableLazyStringList(
                value_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.value_ = value_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation) {
            return mergeFrom((org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation other) {
          if (other == org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.getDefaultInstance()) return this;
          if (!other.value_.isEmpty()) {
            if (value_.isEmpty()) {
              value_ = other.value_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValueIsMutable();
              value_.addAll(other.value_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // repeated string value = 1;
        private com.google.protobuf.LazyStringList value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureValueIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = new com.google.protobuf.LazyStringArrayList(value_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public java.util.List<String>
            getValueList() {
          return java.util.Collections.unmodifiableList(value_);
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public int getValueCount() {
          return value_.size();
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public String getValue(int index) {
          return value_.get(index);
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes(int index) {
          return value_.getByteString(index);
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder setValue(
            int index, String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder addValue(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder addAllValue(
            Iterable<String> values) {
          ensureValueIsMutable();
          super.addAll(values, value_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder clearValue() {
          value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder addValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.add(value);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:QuotationPack.Quotation)
      }

      static {
        defaultInstance = new Quotation(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:QuotationPack.Quotation)
    }

    private int bitField0_;
    // required string tradingDate = 1;
    public static final int TRADINGDATE_FIELD_NUMBER = 1;
    private Object tradingDate_;
    /**
     * <code>required string tradingDate = 1;</code>
     */
    public boolean hasTradingDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string tradingDate = 1;</code>
     */
    public String getTradingDate() {
      Object ref = tradingDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tradingDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tradingDate = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTradingDateBytes() {
      Object ref = tradingDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tradingDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .QuotationPack.SecuType secuType = 2 [default = Other];
    public static final int SECUTYPE_FIELD_NUMBER = 2;
    private org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType secuType_;
    /**
     * <code>required .QuotationPack.SecuType secuType = 2 [default = Other];</code>
     */
    public boolean hasSecuType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .QuotationPack.SecuType secuType = 2 [default = Other];</code>
     */
    public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType getSecuType() {
      return secuType_;
    }

    // repeated .QuotationPack.Quotation quotes = 3;
    public static final int QUOTES_FIELD_NUMBER = 3;
    private java.util.List<org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation> quotes_;
    /**
     * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
     */
    public java.util.List<org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation> getQuotesList() {
      return quotes_;
    }
    /**
     * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
     */
    public java.util.List<? extends org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.QuotationOrBuilder>
        getQuotesOrBuilderList() {
      return quotes_;
    }
    /**
     * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
     */
    public int getQuotesCount() {
      return quotes_.size();
    }
    /**
     * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
     */
    public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation getQuotes(int index) {
      return quotes_.get(index);
    }
    /**
     * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
     */
    public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.QuotationOrBuilder getQuotesOrBuilder(
        int index) {
      return quotes_.get(index);
    }

    private void initFields() {
      tradingDate_ = "";
      secuType_ = org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType.Other;
      quotes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTradingDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSecuType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTradingDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, secuType_.getNumber());
      }
      for (int i = 0; i < quotes_.size(); i++) {
        output.writeMessage(3, quotes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTradingDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, secuType_.getNumber());
      }
      for (int i = 0; i < quotes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, quotes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sky.framework.test.protobuf.QuotationMessage.QuotationPack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sky.framework.test.protobuf.QuotationMessage.QuotationPack prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QuotationPack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.sky.framework.test.protobuf.QuotationMessage.QuotationPackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sky.framework.test.protobuf.QuotationMessage.internal_static_QuotationPack_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sky.framework.test.protobuf.QuotationMessage.internal_static_QuotationPack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.class, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Builder.class);
      }

      // Construct using hbec.app.quotation.stream.message.QuotationMessage.QuotationPack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getQuotesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tradingDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        secuType_ = org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType.Other;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (quotesBuilder_ == null) {
          quotes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          quotesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sky.framework.test.protobuf.QuotationMessage.internal_static_QuotationPack_descriptor;
      }

      public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack getDefaultInstanceForType() {
        return org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.getDefaultInstance();
      }

      public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack build() {
        org.sky.framework.test.protobuf.QuotationMessage.QuotationPack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack buildPartial() {
        org.sky.framework.test.protobuf.QuotationMessage.QuotationPack result = new org.sky.framework.test.protobuf.QuotationMessage.QuotationPack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tradingDate_ = tradingDate_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.secuType_ = secuType_;
        if (quotesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            quotes_ = java.util.Collections.unmodifiableList(quotes_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.quotes_ = quotes_;
        } else {
          result.quotes_ = quotesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sky.framework.test.protobuf.QuotationMessage.QuotationPack) {
          return mergeFrom((org.sky.framework.test.protobuf.QuotationMessage.QuotationPack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sky.framework.test.protobuf.QuotationMessage.QuotationPack other) {
        if (other == org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.getDefaultInstance()) return this;
        if (other.hasTradingDate()) {
          bitField0_ |= 0x00000001;
          tradingDate_ = other.tradingDate_;
          onChanged();
        }
        if (other.hasSecuType()) {
          setSecuType(other.getSecuType());
        }
        if (quotesBuilder_ == null) {
          if (!other.quotes_.isEmpty()) {
            if (quotes_.isEmpty()) {
              quotes_ = other.quotes_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureQuotesIsMutable();
              quotes_.addAll(other.quotes_);
            }
            onChanged();
          }
        } else {
          if (!other.quotes_.isEmpty()) {
            if (quotesBuilder_.isEmpty()) {
              quotesBuilder_.dispose();
              quotesBuilder_ = null;
              quotes_ = other.quotes_;
              bitField0_ = (bitField0_ & ~0x00000004);
              quotesBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getQuotesFieldBuilder() : null;
            } else {
              quotesBuilder_.addAllMessages(other.quotes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTradingDate()) {

          return false;
        }
        if (!hasSecuType()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sky.framework.test.protobuf.QuotationMessage.QuotationPack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sky.framework.test.protobuf.QuotationMessage.QuotationPack) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string tradingDate = 1;
      private Object tradingDate_ = "";
      /**
       * <code>required string tradingDate = 1;</code>
       */
      public boolean hasTradingDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string tradingDate = 1;</code>
       */
      public String getTradingDate() {
        Object ref = tradingDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tradingDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string tradingDate = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTradingDateBytes() {
        Object ref = tradingDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tradingDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tradingDate = 1;</code>
       */
      public Builder setTradingDate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tradingDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tradingDate = 1;</code>
       */
      public Builder clearTradingDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tradingDate_ = getDefaultInstance().getTradingDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string tradingDate = 1;</code>
       */
      public Builder setTradingDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tradingDate_ = value;
        onChanged();
        return this;
      }

      // required .QuotationPack.SecuType secuType = 2 [default = Other];
      private org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType secuType_ = org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType.Other;
      /**
       * <code>required .QuotationPack.SecuType secuType = 2 [default = Other];</code>
       */
      public boolean hasSecuType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .QuotationPack.SecuType secuType = 2 [default = Other];</code>
       */
      public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType getSecuType() {
        return secuType_;
      }
      /**
       * <code>required .QuotationPack.SecuType secuType = 2 [default = Other];</code>
       */
      public Builder setSecuType(org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        secuType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .QuotationPack.SecuType secuType = 2 [default = Other];</code>
       */
      public Builder clearSecuType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        secuType_ = org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.SecuType.Other;
        onChanged();
        return this;
      }

      // repeated .QuotationPack.Quotation quotes = 3;
      private java.util.List<org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation> quotes_ =
        java.util.Collections.emptyList();
      private void ensureQuotesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          quotes_ = new java.util.ArrayList<org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation>(quotes_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.QuotationOrBuilder> quotesBuilder_;

      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public java.util.List<org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation> getQuotesList() {
        if (quotesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(quotes_);
        } else {
          return quotesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public int getQuotesCount() {
        if (quotesBuilder_ == null) {
          return quotes_.size();
        } else {
          return quotesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation getQuotes(int index) {
        if (quotesBuilder_ == null) {
          return quotes_.get(index);
        } else {
          return quotesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public Builder setQuotes(
          int index, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation value) {
        if (quotesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuotesIsMutable();
          quotes_.set(index, value);
          onChanged();
        } else {
          quotesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public Builder setQuotes(
          int index, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder builderForValue) {
        if (quotesBuilder_ == null) {
          ensureQuotesIsMutable();
          quotes_.set(index, builderForValue.build());
          onChanged();
        } else {
          quotesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public Builder addQuotes(org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation value) {
        if (quotesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuotesIsMutable();
          quotes_.add(value);
          onChanged();
        } else {
          quotesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public Builder addQuotes(
          int index, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation value) {
        if (quotesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuotesIsMutable();
          quotes_.add(index, value);
          onChanged();
        } else {
          quotesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public Builder addQuotes(
          org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder builderForValue) {
        if (quotesBuilder_ == null) {
          ensureQuotesIsMutable();
          quotes_.add(builderForValue.build());
          onChanged();
        } else {
          quotesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public Builder addQuotes(
          int index, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder builderForValue) {
        if (quotesBuilder_ == null) {
          ensureQuotesIsMutable();
          quotes_.add(index, builderForValue.build());
          onChanged();
        } else {
          quotesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public Builder addAllQuotes(
          Iterable<? extends org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation> values) {
        if (quotesBuilder_ == null) {
          ensureQuotesIsMutable();
          super.addAll(values, quotes_);
          onChanged();
        } else {
          quotesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public Builder clearQuotes() {
        if (quotesBuilder_ == null) {
          quotes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          quotesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public Builder removeQuotes(int index) {
        if (quotesBuilder_ == null) {
          ensureQuotesIsMutable();
          quotes_.remove(index);
          onChanged();
        } else {
          quotesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder getQuotesBuilder(
          int index) {
        return getQuotesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.QuotationOrBuilder getQuotesOrBuilder(
          int index) {
        if (quotesBuilder_ == null) {
          return quotes_.get(index);  } else {
          return quotesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public java.util.List<? extends org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.QuotationOrBuilder>
           getQuotesOrBuilderList() {
        if (quotesBuilder_ != null) {
          return quotesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(quotes_);
        }
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder addQuotesBuilder() {
        return getQuotesFieldBuilder().addBuilder(
            org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.getDefaultInstance());
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder addQuotesBuilder(
          int index) {
        return getQuotesFieldBuilder().addBuilder(
            index, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.getDefaultInstance());
      }
      /**
       * <code>repeated .QuotationPack.Quotation quotes = 3;</code>
       */
      public java.util.List<org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder>
           getQuotesBuilderList() {
        return getQuotesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.QuotationOrBuilder>
          getQuotesFieldBuilder() {
        if (quotesBuilder_ == null) {
          quotesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.Quotation.Builder, org.sky.framework.test.protobuf.QuotationMessage.QuotationPack.QuotationOrBuilder>(
                  quotes_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          quotes_ = null;
        }
        return quotesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:QuotationPack)
    }

    static {
      defaultInstance = new QuotationPack(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:QuotationPack)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_QuotationPack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QuotationPack_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_QuotationPack_Quotation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QuotationPack_Quotation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034pFile/QuotationMessage.proto\"\271\002\n\rQuota" +
      "tionPack\022\023\n\013tradingDate\030\001 \002(\t\0220\n\010secuTyp" +
      "e\030\002 \002(\0162\027.QuotationPack.SecuType:\005Other\022" +
      "(\n\006quotes\030\003 \003(\0132\030.QuotationPack.Quotatio" +
      "n\032\032\n\tQuotation\022\r\n\005value\030\001 \003(\t\"\232\001\n\010SecuTy" +
      "pe\022\014\n\010SZ_Index\020\001\022\014\n\010SZ_Stock\020\002\022\013\n\007SZ_Bon" +
      "d\020\003\022\013\n\007SZ_Fund\020\004\022\t\n\005Other\020\005\022\013\n\007CSIndex\020\006" +
      "\022\n\n\006CSIopv\020\007\022\014\n\010SH_Index\020\010\022\014\n\010SH_Stock\020\t" +
      "\022\013\n\007SH_Bond\020\n\022\013\n\007SH_Fund\020\013B#\n!hbec.app.q" +
      "uotation.stream.message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_QuotationPack_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_QuotationPack_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_QuotationPack_descriptor,
              new String[] { "TradingDate", "SecuType", "Quotes", });
          internal_static_QuotationPack_Quotation_descriptor =
            internal_static_QuotationPack_descriptor.getNestedTypes().get(0);
          internal_static_QuotationPack_Quotation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_QuotationPack_Quotation_descriptor,
              new String[] { "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
